#!/usr/bin/env bash
# Comandi cURL con status code per validare al volo
# Sostituisci <HOST>, <SESSION_ID>, <MANUS_WEBHOOK_SECRET_REALE> con i tuoi valori

echo "⚡ CURL CON STATUS CODE PER VALIDARE AL VOLO"
echo "============================================"
echo "Sostituisci <HOST>, <SESSION_ID>, <MANUS_WEBHOOK_SECRET_REALE> con i tuoi valori"
echo ""

echo "1️⃣ Health GET + HEAD:"
echo "======================"
echo "curl -sS https://<HOST>/webhooks/manus/hooks/health -w \" → %{http_code}\n\""
echo "curl -sS -I https://<HOST>/webhooks/manus/hooks/health -w \" → %{http_code}\n\" | head -n1"
echo ""

echo "2️⃣ Admin senza auth (negativo):"
echo "================================"
echo "curl -sS -X POST https://<HOST>/admin/manus/mapping/create \\"
echo "  -H \"Content-Type: application/json\" \\"
echo "  -d '{\"manus_user_id\":\"u_test\",\"syn_user_id\":42,\"email\":\"test@example.com\"}' \\"
echo "  -w \" → %{http_code}\n\""
echo ""

echo "3️⃣ Admin con auth (positivo):"
echo "=============================="
echo "curl -sS -X POST https://<HOST>/admin/manus/mapping/create \\"
echo "  -H \"Content-Type: application/json\" \\"
echo "  -H \"Cookie: session=<SESSION_ID>\" \\"
echo "  -d '{\"manus_user_id\":\"u_test\",\"syn_user_id\":42,\"email\":\"test@example.com\"}' \\"
echo "  -w \" → %{http_code}\n\""
echo ""

echo "4️⃣ Webhook firma sbagliata (negativo):"
echo "======================================"
echo "BAD_SIG=deadbeef"
echo "BODY='{\"course_id\":\"COURSE123\",\"manus_user_id\":\"u_test\",\"email\":\"test@example.com\"}'"
echo "curl -sS -X POST https://<HOST>/webhooks/manus/hooks \\"
echo "  -H \"X-Manus-Event: COURSE_COMPLETED\" \\"
echo "  -H \"X-Manus-Signature: \$BAD_SIG\" \\"
echo "  -H \"Content-Type: application/json\" \\"
echo "  -d \"\$BODY\" \\"
echo "  -w \" → %{http_code}\n\""
echo ""

echo "5️⃣ Webhook firma corretta (positivo):"
echo "====================================="
echo "SECRET='<MANUS_WEBHOOK_SECRET_REALE>'"
echo "BODY='{\"course_id\":\"COURSE123\",\"manus_user_id\":\"u_test\",\"email\":\"test@example.com\"}'"
echo "SIG=\$(printf \"%s\" \"\$BODY\" | openssl dgst -sha256 -hmac \"\$SECRET\" -r | awk '{print \$1}')"
echo "curl -sS -X POST https://<HOST>/webhooks/manus/hooks \\"
echo "  -H \"X-Manus-Event: COURSE_COMPLETED\" \\"
echo "  -H \"X-Manus-Signature: \$SIG\" \\"
echo "  -H \"Content-Type: application/json\" \\"
echo "  -d \"\$BODY\" \\"
echo "  -w \" → %{http_code}\n\""
echo ""

echo "6️⃣ Coverage rebuild:"
echo "===================="
echo "curl -sS -X POST https://<HOST>/admin/manus/coverage/rebuild/42 \\"
echo "  -H \"Cookie: session=<SESSION_ID>\" \\"
echo "  -w \" → %{http_code}\n\""
echo ""

echo "🔍 Verifiche DB rapide (opzionali):"
echo "==================================="
echo "sqlite3 gestione.db 'SELECT COUNT(*) FROM manus_user_mapping;'"
echo "sqlite3 gestione.db 'SELECT COUNT(*) FROM training_coverage_report;'"
echo ""

echo "📊 Risultati attesi:"
echo "===================="
echo "• Health GET/HEAD: → 200"
echo "• Admin senza auth: → 401/403"
echo "• Admin con auth: → 200"
echo "• Webhook firma sbagliata: → 401"
echo "• Webhook firma corretta: → 200"
echo "• Coverage rebuild: → 200"
echo ""

echo "🚨 Troubleshooting rapido:"
echo "=========================="
echo "• 401/403 su admin → manca Cookie/Token"
echo "• 401 su webhook → secret/firma: ricalcola SIG dal body identico"
echo "• 200 ma coverage invariato → crea mapping (test 3) → rifai rebuild (test 6)"
echo "• Timeout/504 → journalctl -u gunicorn -n 80 --no-pager e riprova"
