#!/usr/bin/env bash
# Mini check finale prima del via
# Sostituisci <HOST>, <SESSION_ID>, <MANUS_WEBHOOK_SECRET_REALE> con i tuoi valori

echo "🔍 MINI CHECK FINALE PRIMA DEL VIA"
echo "=================================="
echo "Sostituisci <HOST>, <SESSION_ID>, <MANUS_WEBHOOK_SECRET_REALE> con i tuoi valori"
echo ""

echo "📋 CHECK LIST:"
echo "• Health deve dare 200 sia in GET che in HEAD"
echo "• Le admin route richiedono Cookie/Token (atteso 401/403 senza)"
echo "• La firma HMAC va calcolata sul body esatto che invii"
echo ""

echo "🧪 TEST RAPIDI CON STATUS CODE:"
echo "================================"

echo "1️⃣ Health GET + HEAD:"
echo "curl -sS https://<HOST>/webhooks/manus/hooks/health -w \" → %{http_code}\n\""
echo "curl -sS -I https://<HOST>/webhooks/manus/hooks/health -w \" → %{http_code}\n\" | head -n1"
echo "Atteso: 200 per entrambi"
echo ""

echo "2️⃣ Admin senza auth (negativo):"
echo "curl -sS -X POST https://<HOST>/admin/manus/mapping/create \\"
echo "  -H \"Content-Type: application/json\" \\"
echo "  -d '{\"manus_user_id\":\"u_test\",\"syn_user_id\":42,\"email\":\"test@example.com\"}' \\"
echo "  -w \" → %{http_code}\n\""
echo "Atteso: 401 o 403"
echo ""

echo "3️⃣ Admin con auth (positivo):"
echo "curl -sS -X POST https://<HOST>/admin/manus/mapping/create \\"
echo "  -H \"Content-Type: application/json\" \\"
echo "  -H \"Cookie: session=<SESSION_ID>\" \\"
echo "  -d '{\"manus_user_id\":\"u_test\",\"syn_user_id\":42,\"email\":\"test@example.com\"}' \\"
echo "  -w \" → %{http_code}\n\""
echo "Atteso: 200"
echo ""

echo "4️⃣ Webhook firma sbagliata (negativo):"
echo "BAD_SIG=deadbeef"
echo "BODY='{\"course_id\":\"COURSE123\",\"manus_user_id\":\"u_test\",\"email\":\"test@example.com\"}'"
echo "curl -sS -X POST https://<HOST>/webhooks/manus/hooks \\"
echo "  -H \"X-Manus-Event: COURSE_COMPLETED\" \\"
echo "  -H \"X-Manus-Signature: \$BAD_SIG\" \\"
echo "  -H \"Content-Type: application/json\" \\"
echo "  -d \"\$BODY\" \\"
echo "  -w \" → %{http_code}\n\""
echo "Atteso: 401"
echo ""

echo "5️⃣ Webhook firma corretta (positivo):"
echo "SECRET='<MANUS_WEBHOOK_SECRET_REALE>'"
echo "BODY='{\"course_id\":\"COURSE123\",\"manus_user_id\":\"u_test\",\"email\":\"test@example.com\"}'"
echo "SIG=\$(printf \"%s\" \"\$BODY\" | openssl dgst -sha256 -hmac \"\$SECRET\" -r | awk '{print \$1}')"
echo "curl -sS -X POST https://<HOST>/webhooks/manus/hooks \\"
echo "  -H \"X-Manus-Event: COURSE_COMPLETED\" \\"
echo "  -H \"X-Manus-Signature: \$SIG\" \\"
echo "  -H \"Content-Type: application/json\" \\"
echo "  -d \"\$BODY\" \\"
echo "  -w \" → %{http_code}\n\""
echo "Atteso: 200"
echo ""

echo "6️⃣ Coverage rebuild:"
echo "curl -sS -X POST https://<HOST>/admin/manus/coverage/rebuild/42 \\"
echo "  -H \"Cookie: session=<SESSION_ID>\" \\"
echo "  -w \" → %{http_code}\n\""
echo "Atteso: 200"
echo ""

echo "🔍 VERIFICHE DB RAPIDE (opzionali):"
echo "==================================="
echo "sqlite3 gestione.db 'SELECT COUNT(*) FROM manus_user_mapping;'"
echo "sqlite3 gestione.db 'SELECT COUNT(*) FROM training_coverage_report;'"
echo ""

echo "⚡ TIP PER VALIDARE AL VOLO:"
echo "============================"
echo "Aggiungi -w \" → %{http_code}\n\" ai curl per vedere lo status:"
echo "curl -sS https://<HOST>/webhooks/manus/hooks/health -w \" → %{http_code}\n\""
echo ""

echo "🚨 SE QUALCOSA NON TORNA (super breve):"
echo "======================================="
echo "• 401/403 su admin → manca Cookie/Token"
echo "• 401 su webhook → secret/firma: ricalcola SIG dal body identico"
echo "• 200 ma coverage invariato → crea mapping (test 3) → rifai rebuild (test 6)"
echo "• Timeout/504 → journalctl -u gunicorn -n 80 --no-pager e riprova"
echo ""

echo "🎯 ORDINE DI ESECUZIONE CONSIGLIATO:"
echo "===================================="
echo "1. Health (GET + HEAD) → 200"
echo "2. Admin senza auth → 401/403"
echo "3. Admin con auth → 200"
echo "4. Webhook firma sbagliata → 401"
echo "5. Webhook firma corretta → 200"
echo "6. Coverage rebuild → 200"
echo "7. Verifica DB (opzionale)"
echo ""

echo "✅ Se tutti i test passano → GO-LIVE PRONTO!"
echo "❌ Se qualcosa fallisce → controlla troubleshooting sopra"
