"""update_document_version_model

Revision ID: 089196cf6262
Revises: 3077b327f06b
Create Date: 2025-07-29 16:48:33.447491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '089196cf6262'
down_revision = '3077b327f06b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Rimuovo le operazioni ALTER COLUMN per compatibilità SQLite
    op.add_column('document_versions', sa.Column('version_number', sa.Integer(), nullable=True))
    op.add_column('document_versions', sa.Column('file_path', sa.String(length=255), nullable=True))
    op.add_column('document_versions', sa.Column('uploaded_by', sa.String(length=150), nullable=True))
    op.add_column('document_versions', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.add_column('document_versions', sa.Column('active', sa.Boolean(), nullable=True))
    op.add_column('document_versions', sa.Column('ai_diff_summary', sa.Text(), nullable=True))
    op.drop_column('document_versions', 'filename')
    op.drop_column('document_versions', 'numero_versione')
    op.drop_column('document_versions', 'data_caricamento')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_versions', sa.Column('data_caricamento', sa.DATETIME(), nullable=True))
    op.add_column('document_versions', sa.Column('numero_versione', sa.VARCHAR(length=10), nullable=False))
    op.add_column('document_versions', sa.Column('filename', sa.VARCHAR(length=255), nullable=False))
    op.drop_column('document_versions', 'ai_diff_summary')
    op.drop_column('document_versions', 'active')
    op.drop_column('document_versions', 'timestamp')
    op.drop_column('document_versions', 'uploaded_by')
    op.drop_column('document_versions', 'file_path')
    op.drop_column('document_versions', 'version_number')
    # ### end Alembic commands ###
