"""add_formazione_models

Revision ID: 3077b327f06b
Revises: 0d584a21ab7b
Create Date: 2025-07-29 15:58:11.307491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3077b327f06b'
down_revision = '0d584a21ab7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eventi_formazione',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titolo', sa.String(length=200), nullable=False),
    sa.Column('descrizione', sa.Text(), nullable=True),
    sa.Column('data_evento', sa.DateTime(), nullable=True),
    sa.Column('durata_ore', sa.Integer(), nullable=True),
    sa.Column('luogo', sa.String(length=200), nullable=True),
    sa.Column('trainer', sa.String(length=100), nullable=True),
    sa.Column('max_partecipanti', sa.Integer(), nullable=True),
    sa.Column('stato', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('insight_ai',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('insight_text', sa.Text(), nullable=False),
    sa.Column('insight_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_by', sa.String(length=100), nullable=True),
    sa.Column('action_taken', sa.Text(), nullable=True),
    sa.Column('affected_users', sa.Text(), nullable=True),
    sa.Column('affected_documents', sa.Text(), nullable=True),
    sa.Column('pattern_data', sa.Text(), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('trasformato_in_task', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titolo', sa.String(length=200), nullable=False),
    sa.Column('descrizione', sa.Text(), nullable=True),
    sa.Column('priorita', sa.String(length=20), nullable=True),
    sa.Column('assegnato_a', sa.String(length=150), nullable=True),
    sa.Column('stato', sa.String(length=20), nullable=True),
    sa.Column('scadenza', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=150), nullable=False),
    sa.Column('insight_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['insight_id'], ['insight_ai.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('insight_qms_ai',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('insight_text', sa.Text(), nullable=False),
    sa.Column('insight_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('stato', sa.String(length=20), nullable=True),
    sa.Column('documento_id', sa.Integer(), nullable=True),
    sa.Column('modulo_qms', sa.String(length=50), nullable=True),
    sa.Column('data_creazione', sa.DateTime(), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('partecipazioni_formazione',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evento_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('data_iscrizione', sa.DateTime(), nullable=True),
    sa.Column('stato_partecipazione', sa.String(length=20), nullable=True),
    sa.Column('firma_presenza_path', sa.String(length=255), nullable=True),
    sa.Column('attestato_path', sa.String(length=255), nullable=True),
    sa.Column('completato', sa.Boolean(), nullable=True),
    sa.Column('data_completamento', sa.DateTime(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['evento_id'], ['eventi_formazione.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document_approval_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('approver_id', sa.Integer(), nullable=False),
    sa.Column('approver_role', sa.String(length=50), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('method', sa.String(length=50), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['approver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('download_denied_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('admin_log', sa.Column('extra_info', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admin_log', 'extra_info')
    op.drop_table('download_denied_logs')
    op.drop_table('document_approval_logs')
    op.drop_table('partecipazioni_formazione')
    op.drop_table('insight_qms_ai')
    op.drop_table('tasks')
    op.drop_table('insight_ai')
    op.drop_table('eventi_formazione')
    # ### end Alembic commands ###
