"""Add firma_immagine to FirmaDocumento

Revision ID: a43c00560750
Revises: add_contenuto_testuale
Create Date: 2025-07-30 05:12:34.226068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a43c00560750'
down_revision = 'add_contenuto_testuale'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('assets')
    op.alter_column('approval_steps', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('approval_steps', 'method',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('approval_steps', 'auto_approval',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text("'false'"))
    op.add_column('document_versions', sa.Column('filename', sa.String(length=255), nullable=False))
    op.add_column('document_versions', sa.Column('filepath', sa.String(length=500), nullable=False))
    op.add_column('document_versions', sa.Column('uploaded_at', sa.DateTime(), nullable=True))
    op.add_column('document_versions', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.alter_column('document_versions', 'uploaded_by',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.Integer(),
               nullable=False)
    op.alter_column('document_versions', 'version_number',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_foreign_key(None, 'document_versions', 'users', ['uploaded_by'], ['id'])
    op.drop_column('document_versions', 'timestamp')
    op.drop_column('document_versions', 'active')
    op.drop_column('document_versions', 'ai_diff_summary')
    op.drop_column('document_versions', 'file_path')
    op.add_column('documents', sa.Column('tag', sa.String(length=100), nullable=True))
    op.add_column('documents', sa.Column('categoria_ai', sa.String(length=100), nullable=True))
    op.add_column('documents', sa.Column('collegato_a_modulo', sa.String(length=50), nullable=True))
    op.add_column('documents', sa.Column('auto_task_generato', sa.Boolean(), nullable=True))
    op.add_column('documents', sa.Column('contenuto_testuale', sa.Text(), nullable=True))
    op.alter_column('documents', 'is_critical',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text("'false'"))
    op.alter_column('documents', 'is_signed',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text("'false'"))
    op.alter_column('documents', 'signed_by_ai',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text("'false'"))
    op.alter_column('documents', 'stato_approvazione',
               existing_type=sa.VARCHAR(length=30),
               nullable=True,
               existing_server_default=sa.text("'bozza'"))
    op.add_column('firme_documenti', sa.Column('ip', sa.String(length=50), nullable=True))
    op.add_column('firme_documenti', sa.Column('firma_immagine', sa.String(length=255), nullable=True))
    op.alter_column('firme_documenti', 'nome_firma',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=200),
               existing_nullable=False)
    op.alter_column('firme_documenti', 'user_agent',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.drop_column('firme_documenti', 'ip_address')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('firme_documenti', sa.Column('ip_address', sa.VARCHAR(length=45), nullable=True))
    op.alter_column('firme_documenti', 'user_agent',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('firme_documenti', 'nome_firma',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=150),
               existing_nullable=False)
    op.drop_column('firme_documenti', 'firma_immagine')
    op.drop_column('firme_documenti', 'ip')
    op.alter_column('documents', 'stato_approvazione',
               existing_type=sa.VARCHAR(length=30),
               nullable=False,
               existing_server_default=sa.text("'bozza'"))
    op.alter_column('documents', 'signed_by_ai',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text("'false'"))
    op.alter_column('documents', 'is_signed',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text("'false'"))
    op.alter_column('documents', 'is_critical',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text("'false'"))
    op.drop_column('documents', 'contenuto_testuale')
    op.drop_column('documents', 'auto_task_generato')
    op.drop_column('documents', 'collegato_a_modulo')
    op.drop_column('documents', 'categoria_ai')
    op.drop_column('documents', 'tag')
    op.add_column('document_versions', sa.Column('file_path', sa.VARCHAR(length=255), nullable=True))
    op.add_column('document_versions', sa.Column('ai_diff_summary', sa.TEXT(), nullable=True))
    op.add_column('document_versions', sa.Column('active', sa.BOOLEAN(), nullable=True))
    op.add_column('document_versions', sa.Column('timestamp', sa.DATETIME(), nullable=True))
    op.drop_constraint(None, 'document_versions', type_='foreignkey')
    op.alter_column('document_versions', 'version_number',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('document_versions', 'uploaded_by',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=150),
               nullable=True)
    op.drop_column('document_versions', 'is_active')
    op.drop_column('document_versions', 'uploaded_at')
    op.drop_column('document_versions', 'filepath')
    op.drop_column('document_versions', 'filename')
    op.alter_column('approval_steps', 'auto_approval',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text("'false'"))
    op.alter_column('approval_steps', 'method',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('approval_steps', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.create_table('assets',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nome', sa.VARCHAR(length=200), nullable=False),
    sa.Column('tipo', sa.VARCHAR(length=50), nullable=False),
    sa.Column('codice', sa.VARCHAR(length=50), nullable=False),
    sa.Column('stato', sa.VARCHAR(length=20), nullable=True),
    sa.Column('data_acquisto', sa.DATE(), nullable=True),
    sa.Column('valore', sa.FLOAT(), nullable=True),
    sa.Column('note', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codice')
    )
    # ### end Alembic commands ###
