"""Add ApprovazioneDocumento model

Revision ID: add_approvazione_documento
Revises: 
Create Date: 2025-07-30 02:30:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_approvazione_documento'
down_revision = 'f2de65d30151'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_approvazioni',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('livello', sa.Integer(), nullable=False),
    sa.Column('ruolo_richiesto', sa.String(length=100), nullable=False),
    sa.Column('utente', sa.String(length=150), nullable=True),
    sa.Column('stato', sa.String(length=50), nullable=True),
    sa.Column('commento', sa.Text(), nullable=True),
    sa.Column('data', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('document_approvazioni')
    # ### end Alembic commands ### 