"""Add contenuto_testuale to Document model

Revision ID: add_contenuto_testuale
Revises: add_asset_and_responsabile
Create Date: 2025-07-30 06:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_contenuto_testuale'
down_revision = 'add_asset_and_responsabile'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('contenuto_testuale', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'contenuto_testuale')
    # ### end Alembic commands ### 