"""Add asset_id and responsabile_id to Document model

Revision ID: add_asset_and_responsabile
Revises: add_firme_documenti
Create Date: 2025-07-30 05:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_asset_and_responsabile'
down_revision = 'add_firme_documenti'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('asset_id', sa.Integer(), nullable=True))
    op.add_column('documents', sa.Column('responsabile_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'documents', 'assets', ['asset_id'], ['id'])
    op.create_foreign_key(None, 'documents', 'users', ['responsabile_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_column('documents', 'responsabile_id')
    op.drop_column('documents', 'asset_id')
    # ### end Alembic commands ### 