"""Add AI classification fields to Document model

Revision ID: add_ai_classification
Revises: add_approvazione_documento
Create Date: 2025-07-30 03:30:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_ai_classification'
down_revision = 'add_approvazione_documento'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('tag', sa.String(length=100), nullable=True))
    op.add_column('documents', sa.Column('categoria_ai', sa.String(length=100), nullable=True))
    op.add_column('documents', sa.Column('collegato_a_modulo', sa.String(length=50), nullable=True))
    op.add_column('documents', sa.Column('auto_task_generato', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'auto_task_generato')
    op.drop_column('documents', 'collegato_a_modulo')
    op.drop_column('documents', 'categoria_ai')
    op.drop_column('documents', 'tag')
    # ### end Alembic commands ### 