"""Baseline + Add nome and cognome fields to User

Revision ID: cee28dda51a1
Revises: 
Create Date: 2025-07-22 10:32:26.745293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cee28dda51a1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nome', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('cognome', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('cognome')
        batch_op.drop_column('nome')

    # ### end Alembic commands ###
