"""Aggiunta modello DocumentoAIInsight per analisi AI documenti

Revision ID: f2de65d30151
Revises: 089196cf6262
Create Date: 2025-07-30 01:58:37.268846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2de65d30151'
down_revision = '089196cf6262'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_ai_insights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('valore', sa.String(length=500), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('approval_steps', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('approval_steps', 'method',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('approval_steps', 'auto_approval',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text("'false'"))
    op.alter_column('document_versions', 'version_number',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('document_versions', 'file_path',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('document_versions', 'uploaded_by',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
    op.alter_column('document_versions', 'note',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('documents', 'is_critical',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text("'false'"))
    op.alter_column('documents', 'is_signed',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text("'false'"))
    op.alter_column('documents', 'signed_by_ai',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text("'false'"))
    op.alter_column('documents', 'stato_approvazione',
               existing_type=sa.VARCHAR(length=30),
               nullable=True,
               existing_server_default=sa.text("'bozza'"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documents', 'stato_approvazione',
               existing_type=sa.VARCHAR(length=30),
               nullable=False,
               existing_server_default=sa.text("'bozza'"))
    op.alter_column('documents', 'signed_by_ai',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text("'false'"))
    op.alter_column('documents', 'is_signed',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text("'false'"))
    op.alter_column('documents', 'is_critical',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text("'false'"))
    op.alter_column('document_versions', 'note',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('document_versions', 'uploaded_by',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
    op.alter_column('document_versions', 'file_path',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('document_versions', 'version_number',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('approval_steps', 'auto_approval',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text("'false'"))
    op.alter_column('approval_steps', 'method',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('approval_steps', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.drop_table('document_ai_insights')
    # ### end Alembic commands ###
